/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksTelegramPollRouteImport } from './routes/hooks/telegram-poll'
import { Route as HooksTelegramDailyReportRouteImport } from './routes/hooks/telegram-daily-report'
import { Route as HooksLumaSyncRouteImport } from './routes/hooks/luma-sync'
import { Route as ApiPublicHooksLumaSyncActiveRouteImport } from './routes/api/public/hooks/luma-sync-active'

const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTelegramPollRoute = HooksTelegramPollRouteImport.update({
  id: '/hooks/telegram-poll',
  path: '/hooks/telegram-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTelegramDailyReportRoute =
  HooksTelegramDailyReportRouteImport.update({
    id: '/hooks/telegram-daily-report',
    path: '/hooks/telegram-daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksLumaSyncRoute = HooksLumaSyncRouteImport.update({
  id: '/hooks/luma-sync',
  path: '/hooks/luma-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLumaSyncActiveRoute =
  ApiPublicHooksLumaSyncActiveRouteImport.update({
    id: '/api/public/hooks/luma-sync-active',
    path: '/api/public/hooks/luma-sync-active',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/luma-sync': typeof HooksLumaSyncRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
  '/api/public/hooks/luma-sync-active': typeof ApiPublicHooksLumaSyncActiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/luma-sync': typeof HooksLumaSyncRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
  '/api/public/hooks/luma-sync-active': typeof ApiPublicHooksLumaSyncActiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/luma-sync': typeof HooksLumaSyncRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
  '/api/public/hooks/luma-sync-active': typeof ApiPublicHooksLumaSyncActiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/luma-sync'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
    | '/api/public/hooks/luma-sync-active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/luma-sync'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
    | '/api/public/hooks/luma-sync-active'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/luma-sync'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
    | '/api/public/hooks/luma-sync-active'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EventosRoute: typeof EventosRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  PessoasRoute: typeof PessoasRoute
  HooksLumaSyncRoute: typeof HooksLumaSyncRoute
  HooksTelegramDailyReportRoute: typeof HooksTelegramDailyReportRoute
  HooksTelegramPollRoute: typeof HooksTelegramPollRoute
  ApiPublicHooksLumaSyncActiveRoute: typeof ApiPublicHooksLumaSyncActiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/telegram-poll': {
      id: '/hooks/telegram-poll'
      path: '/hooks/telegram-poll'
      fullPath: '/hooks/telegram-poll'
      preLoaderRoute: typeof HooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/telegram-daily-report': {
      id: '/hooks/telegram-daily-report'
      path: '/hooks/telegram-daily-report'
      fullPath: '/hooks/telegram-daily-report'
      preLoaderRoute: typeof HooksTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/luma-sync': {
      id: '/hooks/luma-sync'
      path: '/hooks/luma-sync'
      fullPath: '/hooks/luma-sync'
      preLoaderRoute: typeof HooksLumaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/luma-sync-active': {
      id: '/api/public/hooks/luma-sync-active'
      path: '/api/public/hooks/luma-sync-active'
      fullPath: '/api/public/hooks/luma-sync-active'
      preLoaderRoute: typeof ApiPublicHooksLumaSyncActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EventosRoute: EventosRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  PessoasRoute: PessoasRoute,
  HooksLumaSyncRoute: HooksLumaSyncRoute,
  HooksTelegramDailyReportRoute: HooksTelegramDailyReportRoute,
  HooksTelegramPollRoute: HooksTelegramPollRoute,
  ApiPublicHooksLumaSyncActiveRoute: ApiPublicHooksLumaSyncActiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
