/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksTelegramPollRouteImport } from './routes/hooks/telegram-poll'
import { Route as HooksTelegramDailyReportRouteImport } from './routes/hooks/telegram-daily-report'

const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTelegramPollRoute = HooksTelegramPollRouteImport.update({
  id: '/hooks/telegram-poll',
  path: '/hooks/telegram-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTelegramDailyReportRoute =
  HooksTelegramDailyReportRouteImport.update({
    id: '/hooks/telegram-daily-report',
    path: '/hooks/telegram-daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/eventos': typeof EventosRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/hooks/telegram-daily-report': typeof HooksTelegramDailyReportRoute
  '/hooks/telegram-poll': typeof HooksTelegramPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/eventos'
    | '/import'
    | '/login'
    | '/pessoas'
    | '/hooks/telegram-daily-report'
    | '/hooks/telegram-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EventosRoute: typeof EventosRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  PessoasRoute: typeof PessoasRoute
  HooksTelegramDailyReportRoute: typeof HooksTelegramDailyReportRoute
  HooksTelegramPollRoute: typeof HooksTelegramPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/telegram-poll': {
      id: '/hooks/telegram-poll'
      path: '/hooks/telegram-poll'
      fullPath: '/hooks/telegram-poll'
      preLoaderRoute: typeof HooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/telegram-daily-report': {
      id: '/hooks/telegram-daily-report'
      path: '/hooks/telegram-daily-report'
      fullPath: '/hooks/telegram-daily-report'
      preLoaderRoute: typeof HooksTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EventosRoute: EventosRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  PessoasRoute: PessoasRoute,
  HooksTelegramDailyReportRoute: HooksTelegramDailyReportRoute,
  HooksTelegramPollRoute: HooksTelegramPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
