// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getServerSupabaseConfig() {
  const supabaseUrl = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const publishableKey =
    process.env.SUPABASE_PUBLISHABLE_KEY ??
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
    process.env.VITE_SUPABASE_ANON_KEY;

  if (!supabaseUrl) {
    throw new Error(
      'Missing Supabase server environment variables. Ensure SUPABASE_URL (or VITE_SUPABASE_URL) is set.'
    );
  }

  const serverKey = serviceRoleKey ?? publishableKey;

  if (!serverKey) {
    throw new Error(
      'Missing Supabase server environment variables. Ensure SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY is set.'
    );
  }

  if (!serviceRoleKey) {
    console.warn(
      'SUPABASE_SERVICE_ROLE_KEY is missing in this runtime. Falling back to SUPABASE_PUBLISHABLE_KEY for server requests.'
    );
  }

  return { supabaseUrl, serverKey };
}

function createSupabaseAdminClient() {
  const { supabaseUrl, serverKey } = getServerSupabaseConfig();

  return createClient<Database>(supabaseUrl, serverKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
